export const getProfile = (state) => {return state.profilePage.profile}
export const getaboutMe = (state) => {return state.profilePage.aboutMe}
export const getcontacts = (state) => {return state.profilePage.contacts}
export const getlookingForAJob = (state) => {return state.profilePage.lookingForAJob}
export const getlookingForAJobDescription = (state) => {return state.profilePage.lookingForAJobDescription}
export const getfullName = (state) => {return state.profilePage.fullName}
export const getstatus = (state) => {return state.profilePage.status}
export const getavtorizationUserId = (state) => {return state.autorization.id}
export const getIsAuth = (state) => {return state.autorization.IsAuth}
